# Form implementation generated from reading ui file 'DataManage.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DataManage(object):
    def setupUi(self, DataManage):
        DataManage.setObjectName("DataManage")
        DataManage.resize(1000, 600)
        DataManage.setStyleSheet("background-color: white;")
        self.pushButton = QtWidgets.QPushButton(parent=DataManage)
        self.pushButton.setGeometry(QtCore.QRect(670, 250, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=DataManage)
        self.pushButton_2.setGeometry(QtCore.QRect(670, 320, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=DataManage)
        self.lineEdit.setGeometry(QtCore.QRect(360, 250, 291, 41))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=DataManage)
        self.lineEdit_2.setGeometry(QtCore.QRect(360, 320, 291, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(parent=DataManage)
        self.label.setGeometry(QtCore.QRect(280, 250, 54, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=DataManage)
        self.label_2.setGeometry(QtCore.QRect(280, 320, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(parent=DataManage)
        self.line.setGeometry(QtCore.QRect(330, 250, 20, 111))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.label_3 = QtWidgets.QLabel(parent=DataManage)
        self.label_3.setGeometry(QtCore.QRect(400, 140, 200, 71))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(DataManage)
        QtCore.QMetaObject.connectSlotsByName(DataManage)

    def retranslateUi(self, DataManage):
        _translate = QtCore.QCoreApplication.translate
        DataManage.setWindowTitle(_translate("DataManage", "Form"))
        self.pushButton.setText(_translate("DataManage", "추가"))
        self.pushButton_2.setText(_translate("DataManage", "삭제"))
        self.lineEdit.setPlaceholderText(_translate("DataManage", "ex: scent"))
        self.lineEdit_2.setPlaceholderText(_translate("DataManage", "ex: 향기"))
        self.label.setText(_translate("DataManage", "단어"))
        self.label_2.setText(_translate("DataManage", "뜻"))
        self.label_3.setText(_translate("DataManage", "단어장 관리"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DataManage = QtWidgets.QWidget()
    ui = Ui_DataManage()
    ui.setupUi(DataManage)
    DataManage.show()
    sys.exit(app.exec())
