# Form implementation generated from reading ui file 'EngTest.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EnglishTest(object):
    def setupUi(self, EnglishTest):
        EnglishTest.setObjectName("EnglishTest")
        EnglishTest.setEnabled(True)
        EnglishTest.resize(1000, 600)
        # EnglishTest.setStyleSheet("background-color: white;")
        self.centralwidget = QtWidgets.QWidget(parent=EnglishTest)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(624, 350, 75, 50))
        self.pushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton.setMaximumSize(QtCore.QSize(75, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(300, 240, 400, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setStyleSheet("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(300, 351, 321, 45))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 130, 401, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(300, 200, 400, 3))
        self.line.setMinimumSize(QtCore.QSize(400, 0))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        EnglishTest.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=EnglishTest)
        self.statusbar.setObjectName("statusbar")
        EnglishTest.setStatusBar(self.statusbar)

        self.retranslateUi(EnglishTest)
        QtCore.QMetaObject.connectSlotsByName(EnglishTest)

    def retranslateUi(self, EnglishTest):
        _translate = QtCore.QCoreApplication.translate
        EnglishTest.setWindowTitle(_translate("EnglishTest", "MainWindow"))
        self.pushButton.setText(_translate("EnglishTest", "제출"))
        self.lineEdit.setPlaceholderText(_translate("EnglishTest", "답 입력"))
        self.label.setText(_translate("EnglishTest", "단어 테스트"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EnglishTest = QtWidgets.QMainWindow()
    ui = Ui_EnglishTest()
    ui.setupUi(EnglishTest)
    EnglishTest.show()
    sys.exit(app.exec())
