# Form implementation generated from reading ui file 'GameSelectWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GameSelectWindow(object):
    def setupUi(self, GameSelectWindow):
        GameSelectWindow.setObjectName("GameSelectWindow")
        GameSelectWindow.resize(1000, 600)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=GameSelectWindow)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(80, 240, 841, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.perfectStreakButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.perfectStreakButton.sizePolicy().hasHeightForWidth())
        self.perfectStreakButton.setSizePolicy(sizePolicy)
        self.perfectStreakButton.setMinimumSize(QtCore.QSize(300, 70))
        self.perfectStreakButton.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.perfectStreakButton.setFont(font)
        self.perfectStreakButton.setObjectName("perfectStreakButton")
        self.gridLayout.addWidget(self.perfectStreakButton, 0, 0, 1, 1)
        self.timeAttackButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.timeAttackButton.setMinimumSize(QtCore.QSize(300, 70))
        self.timeAttackButton.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.timeAttackButton.setFont(font)
        self.timeAttackButton.setObjectName("timeAttackButton")
        self.gridLayout.addWidget(self.timeAttackButton, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=GameSelectWindow)
        self.label.setGeometry(QtCore.QRect(305, 166, 391, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(GameSelectWindow)
        QtCore.QMetaObject.connectSlotsByName(GameSelectWindow)

    def retranslateUi(self, GameSelectWindow):
        _translate = QtCore.QCoreApplication.translate
        GameSelectWindow.setWindowTitle(_translate("GameSelectWindow", "Dialog"))
        self.perfectStreakButton.setText(_translate("GameSelectWindow", "도장 깨기"))
        self.timeAttackButton.setText(_translate("GameSelectWindow", "타임 어택"))
        self.label.setText(_translate("GameSelectWindow", "도전하고 싶은 게임을 선택하세요."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GameSelectWindow = QtWidgets.QDialog()
    ui = Ui_GameSelectWindow()
    ui.setupUi(GameSelectWindow)
    GameSelectWindow.show()
    sys.exit(app.exec())
