# Form implementation generated from reading ui file 'MeanTest.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MeanTest(object):
    def setupUi(self, MeanTest):
        MeanTest.setObjectName("MeanTest")
        MeanTest.resize(1000, 600)
        # MeanTest.setStyleSheet("background-color: white;")
        self.centralwidget = QtWidgets.QWidget(parent=MeanTest)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(624, 350, 75, 50))
        self.pushButton.setMaximumSize(QtCore.QSize(75, 50))
        self.pushButton.setObjectName("pushButton")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(300, 240, 400, 81))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(300, 351, 321, 45))
        self.lineEdit.setObjectName("lineEdit")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(300, 200, 400, 3))
        self.line.setMinimumSize(QtCore.QSize(400, 0))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 130, 401, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        MeanTest.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MeanTest)
        self.statusbar.setObjectName("statusbar")
        MeanTest.setStatusBar(self.statusbar)

        self.retranslateUi(MeanTest)
        QtCore.QMetaObject.connectSlotsByName(MeanTest)

    def retranslateUi(self, MeanTest):
        _translate = QtCore.QCoreApplication.translate
        MeanTest.setWindowTitle(_translate("MeanTest", "MeanTest"))
        self.pushButton.setText(_translate("MeanTest", "제출"))
        self.lineEdit.setPlaceholderText(_translate("MeanTest", "답 입력"))
        self.label.setText(_translate("MeanTest", "뜻 테스트"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MeanTest = QtWidgets.QMeanTest()
    ui = Ui_MeanTest()
    ui.setupUi(MeanTest)
    MeanTest.show()
    sys.exit(app.exec())
