# Form implementation generated from reading ui file 'perfect_streak.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PerfectStreak(object):
    def setupUi(self, PerfectStreak):
        PerfectStreak.setObjectName("PerfectStreak")
        PerfectStreak.resize(1000, 600)
        self.centralwidget = QtWidgets.QWidget(parent=PerfectStreak)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(724, 298, 75, 50))
        self.pushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton.setMaximumSize(QtCore.QSize(75, 31))
        self.pushButton.setObjectName("pushButton")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(400, 210, 400, 80))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(400, 300, 321, 45))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 130, 241, 271))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(350, 90, 20, 381))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        PerfectStreak.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=PerfectStreak)
        self.statusbar.setObjectName("statusbar")
        PerfectStreak.setStatusBar(self.statusbar)

        self.retranslateUi(PerfectStreak)
        QtCore.QMetaObject.connectSlotsByName(PerfectStreak)

    def retranslateUi(self, PerfectStreak):
        _translate = QtCore.QCoreApplication.translate
        PerfectStreak.setWindowTitle(_translate("PerfectStreak", "MainWindow"))
        self.pushButton.setText(_translate("PerfectStreak", "제출"))
        self.label.setText(_translate("PerfectStreak", "<html><head/><body><p>게임: <span style=\" color:#397eff;\">도장깨기</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PerfectStreak = QtWidgets.QMainWindow()
    ui = Ui_PerfectStreak()
    ui.setupUi(PerfectStreak)
    PerfectStreak.show()
    sys.exit(app.exec())
