# Form implementation generated from reading ui file 'settings_window_theme.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SettingThema(object):
    def setupUi(self, SettingThema):
        SettingThema.setObjectName("SettingThema")
        SettingThema.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=SettingThema)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 90, 211, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(230, 10, 20, 551))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.radioButton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(300, 90, 451, 100))
        self.radioButton.setMinimumSize(QtCore.QSize(50, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.radioButton.setFont(font)
        self.radioButton.setStyleSheet("border : 1px solid white;")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(300, 210, 451, 100))
        self.radioButton_2.setMinimumSize(QtCore.QSize(50, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("border : 1px solid black;")
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(300, 330, 451, 100))
        self.radioButton_3.setMinimumSize(QtCore.QSize(50, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setStyleSheet("border : 1px solid green;")
        self.radioButton_3.setObjectName("radioButton_3")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(400, 480, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.exitButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(760, 10, 21, 32))
        self.exitButton.setObjectName("exitButton")
        self.menuButtonTheme = QtWidgets.QCommandLinkButton(parent=self.centralwidget)
        self.menuButtonTheme.setGeometry(QtCore.QRect(30, 210, 168, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.menuButtonTheme.setFont(font)
        self.menuButtonTheme.setObjectName("menuButtonTheme")
        SettingThema.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=SettingThema)
        self.statusbar.setObjectName("statusbar")
        SettingThema.setStatusBar(self.statusbar)

        self.retranslateUi(SettingThema)
        QtCore.QMetaObject.connectSlotsByName(SettingThema)

    def retranslateUi(self, SettingThema):
        _translate = QtCore.QCoreApplication.translate
        SettingThema.setWindowTitle(_translate("SettingThema", "MainWindow"))
        self.label.setText(_translate("SettingThema", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:700;\">설정</span></p></body></html>"))
        self.radioButton.setText(_translate("SettingThema", "light"))
        self.radioButton_2.setText(_translate("SettingThema", "dark"))
        self.radioButton_3.setText(_translate("SettingThema", "plant"))
        self.pushButton.setText(_translate("SettingThema", "저장"))
        self.exitButton.setText(_translate("SettingThema", "X"))
        self.menuButtonTheme.setText(_translate("SettingThema", "테마 변경"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SettingThema = QtWidgets.QMainWindow()
    ui = Ui_SettingThema()
    ui.setupUi(SettingThema)
    SettingThema.show()
    sys.exit(app.exec())
