# Form implementation generated from reading ui file 'time_attack.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TimeAttack(object):
    def setupUi(self, TimeAttack):
        TimeAttack.setObjectName("TimeAttack")
        TimeAttack.resize(1000, 600)
        self.centralwidget = QtWidgets.QWidget(parent=TimeAttack)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(724, 268, 75, 50))
        self.pushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton.setMaximumSize(QtCore.QSize(75, 50))
        self.pushButton.setObjectName("pushButton")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(400, 188, 400, 80))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(400, 270, 321, 45))
        self.lineEdit.setObjectName("lineEdit")
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(400, 320, 401, 50))
        self.progressBar.setProperty("value", 49)
        self.progressBar.setObjectName("progressBar")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(350, 110, 20, 381))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 130, 241, 271))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        TimeAttack.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=TimeAttack)
        self.statusbar.setObjectName("statusbar")
        TimeAttack.setStatusBar(self.statusbar)

        self.retranslateUi(TimeAttack)
        QtCore.QMetaObject.connectSlotsByName(TimeAttack)

    def retranslateUi(self, TimeAttack):
        _translate = QtCore.QCoreApplication.translate
        TimeAttack.setWindowTitle(_translate("TimeAttack", "MainWindow"))
        self.pushButton.setText(_translate("TimeAttack", "제출"))
        self.label.setText(_translate("TimeAttack", "<html><head/><body><p>게임:<span style=\" color:#397eff;\"> 타임어택</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TimeAttack = QtWidgets.QMainWindow()
    ui = Ui_TimeAttack()
    ui.setupUi(TimeAttack)
    TimeAttack.show()
    sys.exit(app.exec())
